version: "3.4"

services:
  app:
    build:
      context: .
      dockerfile: build/golang/Dockerfile
    ports:
      - '8080:${HTTP_EXTERNAL_PORT}'
    restart: unless-stopped #Restart container until database is ready.
    depends_on:
      - postgres
    command: sh -c "/wait && ./main" #Wait until postgres is built.
    environment:
      WAIT_HOSTS: postgres:5432 #Configure wait host and port.
    volumes:
      - ./log/go/:/app/log/go/
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_USER_PASSWD}
    ports:
      - '5432:${POSTGRES_EXTERNAL_PORT}'
    volumes:
      - ./postgres_db:/var/lib/postgresql/data
